# Generated by Django 4.0 on 2022-01-16 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='tags',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Blog',
            new_name='blog',
        ),
    ]
