# Generated by Django 4.0 on 2022-02-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto1', '0003_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='descripcion',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avatar',
            name='link',
            field=models.URLField(default='http://'),
            preserve_default=False,
        ),
    ]
