# Generated by Django 4.0 on 2022-02-05 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto1', '0003_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='imagen',
            field=models.ImageField(null=True, upload_to='blogi'),
        ),
    ]
