# Generated by Django 4.0 on 2022-02-09 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto1', '0005_blog_publicacion_alter_blog_body_alter_blog_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publicacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
