# Generated by Django 4.0 on 2022-02-10 01:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto1', '0006_alter_blog_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='fechaCreacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='blog',
            name='publicacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
