# Generated by Django 4.0 on 2022-02-10 02:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto1', '0007_blog_fechacreacion_alter_blog_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publicacion',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
