# Generated by Django 4.0 on 2022-02-13 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto1', '0004_avatar_descripcion_avatar_link'),
        ('AppProyecto1', '0008_alter_blog_publicacion'),
    ]

    operations = [
    ]
