# Generated by Django 4.0 on 2022-02-14 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('AppProyecto1', '0009_merge_20220213_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('created_at', models.TimeField()),
                ('receptor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='receptor', to='auth.user')),
                ('remitente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='remitente', to='auth.user')),
            ],
        ),
    ]
