# Generated by Django 4.0 on 2022-02-14 23:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto1', '0011_alter_mensajeria_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajeria',
            name='contenido',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
