# Generated by Django 4.0 on 2022-02-15 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto1', '0011_alter_blog_autor_delete_author'),
        ('AppProyecto1', '0012_alter_mensajeria_contenido'),
    ]

    operations = [
    ]
